name: proyecto_vehiculos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  datetime_picker_formfield: ^2.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_date_pickers: ^0.4.2
  intl: ^0.18.1
  path: ^1.8.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+3
  sqflite_common_ffi_web: ^0.4.0
  syncfusion_flutter_datepicker: ^23.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
